version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.44.0
    steps:
      - run: 
          name: "Set NEMU_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspaces/projects/nemu/cpp && echo 'export NEMU_CPP_ROOT="/workspaces/projects/nemu/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Nemu/C++ Core"
          command: cd /workspaces/projects/nemu/cpp && git clone https://github.com/nemu-cpp/core.git && cd core/build-files/gnumake && make
      - run:
          name: "Install build dependency: Nemu/C++ WebFramework"
          command: cd /workspaces/projects/nemu/cpp && git clone https://github.com/nemu-cpp/web-framework.git && cd web-framework/build-files/gnumake && make
      - checkout:
          path: /workspaces/projects/nemu/cpp/mustache-template-engine
      - run:
          name: Build
          command: cd /workspaces/projects/nemu/cpp/mustache-template-engine/build-files/gnumake && make
      - run:
          name: Test
          command: cd /workspaces/projects/nemu/cpp/mustache-template-engine/tests/build-files/gnumake && make && ./NemuMustacheTemplateEngineTests
      - run:
          name: Build MustacheTemplates example
          command: cd /workspaces/projects/nemu/cpp/mustache-template-engine/examples/mustache-templates/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
